### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by isteptoe** [joshuawootonn/type-the-word#5]
Thanks for creating this! I was thinking about making something similarfor myself but found this, which is much better than anything I could have done.

I have two feature requests that I think would make it even better:
1. Would it be possible to have the site remember the last location the signed in user was at? As far as I can tell, it always defaults to Psalm 23. It would be great if I could navigate to the site and be right where I left off.
2. At the end of a chapter, when you type Space, can you make it go to the next chapter (and book if applicable) so you don't have to go through the chapter picker?

**Comment by joshuawootonn** [comment]
Hey @isteptoe! Glad to hear the project has been helpful. 

I think those are great ideas. I am currently working on another project, but I'll consider batching these up when I get back to working on Type the Word.
